version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: gcc:4.9
    steps:
      - checkout
      - run:
          name: Build
          command: |
            gcc *.c utiles.o -o defendiendo -std=c99 -Wconversion
      - run:
          name: Test
          command: |
            cd tests
            gcc tests.c -o tests
            ./tests